using System;
using System.IO;
using System.Linq;
using Backer.Desktop.Services;
using Xunit;

namespace Backer.Desktop.Tests;

/// <summary>
/// The other half of the cross-language metadata contract. Fixtures/data/ is generated by the
/// real Python writers (tests/test_metadata_fixtures.py, which fails if they change) and read
/// here through the real deserialisers, so a reader that stops binding a field fails dotnet CI.
/// Every field asserted here is one the UI displays; fix the C# model, never the fixture.
/// </summary>
public sealed class MetadataFixtureTests
{
    private static readonly DataDirStore Store =
        new(Path.Combine(AppContext.BaseDirectory, "Fixtures", "data"));

    [Fact]
    public void LastAttemptBindsEveryDisplayedField()
    {
        var run = Store.LastAttempt("Daily Docs");

        Assert.NotNull(run);
        Assert.Equal("Daily Docs", run!.JobName);
        Assert.Equal("20260902T030000Z-1a2b3c4d", run.RunId);
        Assert.Equal("success", run.Status);
        Assert.Equal("2026-09-02T02:30:00Z", run.StartedAt);
        Assert.Equal("2026-09-02T02:34:11Z", run.FinishedAt);
        Assert.Equal("9f8e7d6c5b4a", run.RepositoryId);
        Assert.Equal("1a2b3c4d", run.ClientId);
        Assert.False(run.NeedsInput);
        // HomeViewModel renders Result.BytesTransferred; a null Result there prints "—" forever.
        Assert.NotNull(run.Result);
        Assert.True(run.Result!.Success);
        Assert.Equal(1234, run.Result.BytesTransferred);
        Assert.Equal(42, run.Result.FilesTransferred);
        Assert.Equal(251.0, run.Result.DurationSeconds);
        Assert.NotNull(run.Result.Errors);
    }

    [Fact]
    public void RunHistoryBindsTheFailureShapeNewestFirst()
    {
        var runs = Store.Runs("Daily Docs");

        Assert.Equal(
            new[] { "20260902T030000Z-1a2b3c4d", "20260902T020000Z-1a2b3c4d" },
            runs.Select(run => run.RunId));

        var failed = runs[1];
        Assert.Equal("failed", failed.Status);
        Assert.Equal("connect", failed.ErrorStage);
        Assert.True(failed.NeedsInput);
        Assert.Equal("failed to open repository: invalid repository password", failed.ErrorMessage);
        Assert.NotNull(failed.Result);
        Assert.False(failed.Result!.Success);
        Assert.Equal(
            new[] { "failed to open repository: invalid repository password" },
            failed.Result.Errors!);
    }

    [Fact]
    public void ProgressFrameBindsTheRunningShape()
    {
        var frame = Store.Progress("20260902T040000Z-1a2b3c4d");

        Assert.NotNull(frame);
        Assert.Equal("20260902T040000Z-1a2b3c4d", frame!.RunId);
        Assert.Equal("running", frame.Status);
        Assert.Equal(524288, frame.BytesProcessed);
        Assert.Equal(2097152, frame.TotalBytes);
        Assert.Equal(12, frame.FilesProcessed);
        Assert.Equal(40, frame.TotalFiles);
        Assert.Equal(400000, frame.HashedBytes);
        Assert.Equal(124288, frame.CachedBytes);
    }

    /// <summary>
    /// total_bytes is the previous snapshot's size, so a grown source exceeds it. The writer then
    /// nulls the denominator rather than reporting a percentage it cannot compute, and the reader
    /// must render that as indeterminate — not as "0 bytes to go".
    /// </summary>
    [Fact]
    public void ExceededEstimateBindsAsUnknownRatherThanZero()
    {
        var frame = Store.Progress("20260902T050000Z-1a2b3c4d");

        Assert.NotNull(frame);
        Assert.Null(frame!.TotalBytes);
        Assert.Equal(4274834636, frame.BytesProcessed);
        Assert.Equal(200, frame.FilesProcessed);
    }

    [Fact]
    public void PauseStateBinds()
    {
        var pause = Store.Pause();

        Assert.True(pause.Paused);
        Assert.Equal("2026-09-03T09:00:00Z", pause.Until);
    }
}
