"""Cross-language drift guard for the on-disk metadata contract.

The desktop client reads `<data_dir>` directly (D8), so the Python writers and the C#
deserialisers are two halves of one contract with nothing between them to catch drift.
These fixtures are generated by the REAL writers and committed under
`desktop/Backer.Desktop.Tests/Fixtures/data/`; this test fails if a Python writer changes
their bytes, and `MetadataFixtureTests` fails if a C# reader stops binding them.

Regenerate deliberately with `BACKER_REGENERATE_FIXTURES=1 pytest tests/test_metadata_fixtures.py`
and run the dotnet tests before committing the result.
"""

from __future__ import annotations

import os
from datetime import UTC, datetime
from pathlib import Path

from backer.backends.base import BackendResult, OperationType
from backer.core.job import JobRun, JobStatus
from backer.serverless.runs import _write_progress
from backer.serverless.schedule import schedule_pause
from backer.serverless.store import append_run

FIXTURES = Path(__file__).resolve().parents[1] / "desktop" / "Backer.Desktop.Tests" / "Fixtures" / "data"

JOB = "Daily Docs"
FAILED_RUN_ID = "20260902T020000Z-1a2b3c4d"
SUCCESS_RUN_ID = "20260902T030000Z-1a2b3c4d"
PROGRESS_RUN_ID = "20260902T040000Z-1a2b3c4d"
ESTIMATE_EXCEEDED_RUN_ID = "20260902T050000Z-1a2b3c4d"


def _run(run_id: str, status: JobStatus, *, minute: int, **fields: object) -> JobRun:
    started = datetime(2026, 9, 2, 2, minute, 0, tzinfo=UTC)
    finished = datetime(2026, 9, 2, 2, minute + 4, 11, tzinfo=UTC)
    return JobRun(
        JOB,
        run_id,
        status,
        started,
        finished,
        result=BackendResult(
            success=status is JobStatus.SUCCESS,
            operation=OperationType.BACKUP,
            started_at=started,
            finished_at=finished,
            bytes_transferred=1234 if status is JobStatus.SUCCESS else 0,
            files_transferred=42 if status is JobStatus.SUCCESS else 0,
            errors=[] if status is JobStatus.SUCCESS else ["failed to open repository: invalid repository password"],
        ),
        client_id="1a2b3c4d",
        repository_id="9f8e7d6c5b4a",
        **fields,  # type: ignore[arg-type]
    )


def generate(data_dir: Path) -> None:
    """Write one of every document the desktop client reads, through its real writer."""
    # Failure first, so last_attempt/ ends up holding the successful run.
    append_run(
        data_dir,
        _run(
            FAILED_RUN_ID,
            JobStatus.FAILED,
            minute=0,
            error_message="failed to open repository: invalid repository password",
            error_stage="connect",
            needs_input=True,
        ),
    )
    append_run(data_dir, _run(SUCCESS_RUN_ID, JobStatus.SUCCESS, minute=30))
    # The running frame runner.py's progress_callback emits (core/runner.py:139-152).
    _write_progress(
        data_dir,
        PROGRESS_RUN_ID,
        status="running",
        current_file="/srv/docs/report.pdf",
        bytes_processed=524288,
        files_processed=12,
        total_bytes=2097152,
        total_files=40,
        hashed_bytes=400000,
        cached_bytes=124288,
        hashed_files=9,
        cached_files=3,
        progress_percent=27,
    )
    # total_bytes is the previous snapshot's size, so a grown source blows past it: the
    # writer then reports the denominator and the percentage as null rather than lying.
    _write_progress(
        data_dir,
        ESTIMATE_EXCEEDED_RUN_ID,
        status="running",
        current_file=None,
        bytes_processed=4274834636,
        files_processed=200,
        total_bytes=800000000,
        total_files=0,
        progress_percent=95,
    )
    schedule_pause(data_dir, True, datetime(2026, 9, 3, 9, 0, 0, tzinfo=UTC))


def _tree(root: Path) -> dict[str, bytes]:
    return {
        str(path.relative_to(root)).replace(os.sep, "/"): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def test_desktop_fixtures_still_match_the_python_writers(tmp_path: Path) -> None:
    generate(tmp_path)
    produced = _tree(tmp_path)

    if os.environ.get("BACKER_REGENERATE_FIXTURES") == "1":  # pragma: no cover - maintenance path
        for path in sorted(FIXTURES.rglob("*"), reverse=True):
            path.unlink() if path.is_file() else path.rmdir()
        for relative, payload in produced.items():
            target = FIXTURES / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(payload)

    assert produced == _tree(FIXTURES), (
        "The desktop metadata fixtures no longer match what the Python writers emit. "
        "A writer change here is a change to the contract the C# reader binds: regenerate with "
        "BACKER_REGENERATE_FIXTURES=1 and run the dotnet tests before committing."
    )
