# Project-wide Gradle settings.

# Enable AndroidX
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enable Gradle build cache
org.gradle.caching=true

# Enable parallel builds
org.gradle.parallel=true

# Configure JVM heap
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable non-transitive R classes
android.nonTransitiveRClass=true

# Enable configuration cache
org.gradle.configuration-cache=true